# Config
exclude: ['robots.txt']

# Dependencies
markdown: rdiscount
pygments: true

# Permalinks
permalink: pretty

# Variables
title: Galaxie
description: Collection Interactive de Planètes
author: Léo Colombaro
